### ISSUE TITLE
Errore di scrittura

### ISSUE THREAD

**Issue by rockplayer007** [Procsiab/ns-2019#1]
Pagina 9 nel paragrafo dell'algoritmo esteso hai scritto
x0 =, x1 = 1; y0 = 1, y1 = 0 
giusto sarebbe
x0 =0 x1 = 1; y0 = 1, y1 = 0

**Comment by Procsiab** [comment]
Grazie per la dritta, ho corretto; rilascerò il commit con le correzioni nel fine settimana così le metto tutte assieme
